### ISSUE TITLE
Markbot 

### ISSUE THREAD

**Issue by mato0039** [mato0039/saas-website#6]
Hi Christina, 

I'm getting a few issues with Markbot: 

1) It wants labels? I have them there but they I added the **hidden** class to them as I don't want them to appear. Is that the issue?

<img width="522" alt="Screen Shot 2020-04-15 at 1 07 24 PM" src="https://user-images.githubusercontent.com/55108737/79366644-8fffba80-7f1a-11ea-9358-ae25f97ca9a4.png">

2) It says the buttons don't have a hover state but they do. Is this because I modified from from the modulifier version?

<img width="514" alt="Screen Shot 2020-04-15 at 1 07 40 PM" src="https://user-images.githubusercontent.com/55108737/79366710-aad22f00-7f1a-11ea-9be0-f095f212dee3.png">

3) The image isn't showing up properly when I add the embed class. Markbot says I have to use embed but I rather just use **img-flex**. How do I fix this?

<img width="1154" alt="Screen Shot 2020-04-15 at 1 08 05 PM" src="https://user-images.githubusercontent.com/55108737/79366814-d228fc00-7f1a-11ea-809b-89854eeb1c8e.png">

@muxlowc

**Comment by muxlowc** [comment]
@mato0039 

1) hmm have you tried putting it through markbot without the hidden class? thats probably it. Technically having only a placeholder is not accessible because when you click on the input, the placeholder disappears, so you might have to have it appear (your placeholder could be "ex. johnsmith@email.com" or something so the wording isnt as redundant.

2) Maybe try going into your modulifier settings and change the colours there, rather than trying to override whats in your modulifier files. Markbot shouldntttt get mad haha

3) So i found that this works: go into your modules.css and under embed-item, remove the position absolute. I think your grids are doing something that doesnt work well with absolute items.

**Comment by mato0039** [comment]
Haha thanks!

Everything worked, apart from the **btn:hover**. Did you mean go to into modules.css and change it there? That's what I did and Markbot doesn't like it. It's the only change I need to make in order to submit...

@muxlowc

**Comment by muxlowc** [comment]
@mato0039 no worries, you can just send me a screenshot of your markbot when you submit your request for grade! I won't dock you marks on that issue at all, so no worries! haha

**Comment by mato0039** [comment]
Ok. So I'll take a screenshot of it now I guess? Because I want to go back and change all the things that Markbot didn't like...lol. 

@muxlowc

**Comment by mato0039** [comment]
It worked. I submitted it. 
Do I submit a request for grade as an issue on GitHub once I'm done?

@muxlowc

**Comment by muxlowc** [comment]
@mato0039 yep, just attach your screenshot of markbot to your request for grade (which should be a new issue on this repository)

**Comment by mato0039** [comment]
Done! 
Also just reminding you that I sent you my progress for the **website check-in** mark. :) 
Take care!

**Comment by muxlowc** [comment]
@mato0039 amazing! thanks for the reminder, your checkin grade has been updated!
